const AI_URL = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions";
const MODEL = "gemini-3.6-flash";

export type FollowUpInput = {
  url: string;
  businessName: string | null;
  bestPitchTitle: string | null;
  result: unknown;
  followUpNumber: number;
  background?: string | null;
  tone?: string | null;
};

export async function generateFollowUp(input: FollowUpInput): Promise<{
  subject: string;
  message: string;
}> {
  const apiKey = process.env["GEMINI_API_KEY"];
  if (!apiKey) throw new Error("Gemini AI is not configured for this project.");

  const system = `You write short, human follow-up outreach messages for a freelance digital consultant.
Context: the consultant already sent a pitch to this business about a specific opportunity.
Write follow-up message number ${input.followUpNumber}.

Rules:
- Keep it under 120 words, plain language, no hype, no buzzwords, no emojis.
- Reference something real and specific from the research provided. Never invent facts.
- Structure the message in this order: personalize, greeting, acknowledge the business, identify the opportunity, show you understand the business, explain the real problem, connect it to time or money, present the opportunity, propose a specific solution, focus on business outcomes, make it customized, establish credibility, reduce risk, end with a simple CTA, keep it short, avoid generic language, avoid criticism, avoid sounding desperate, pitch the problem before the service, give them a reason to reply, focus on their revenue process, make the value obvious, and create curiosity.
- Briefly re-anchor the value of the chosen pitch in one line, add one new angle or small piece of useful value.
- Polite, low-pressure close with a single easy question.
- Do not use hyphens, em dashes, en dashes, bullet symbols, markdown, or phrases such as "AI generated" or "generated by AI".
- Output strictly JSON: {"subject": string, "message": string}. No markdown fences.`;

  const user = `Business URL: ${input.url}
Business name: ${input.businessName ?? "Not available"}
Chosen pitch: ${input.bestPitchTitle ?? "Not available"}
Follow-up number: ${input.followUpNumber}
${input.tone ? `Desired tone: ${input.tone}` : ""}
${input.background ? `Consultant background/services:\n"""\n${input.background.slice(0, 3000)}\n"""` : ""}

Research data (JSON):
${JSON.stringify(input.result).slice(0, 40000)}`;

  const res = await fetch(AI_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    console.error(`AI gateway failed [${res.status}]: ${body}`);
    if (res.status === 429)
      throw new Error("Rate limit reached. Please try again in a moment.");
    if (res.status === 402)
      throw new Error("AI credits exhausted. Add credits to continue.");
    throw new Error(`Follow-up generation failed [${res.status}]`);
  }

  const data = (await res.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const content = data.choices?.[0]?.message?.content?.trim() ?? "";
  const cleaned = content.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  try {
    const parsed = JSON.parse(cleaned) as { subject?: string; message?: string };
    if (parsed.message) {
      return {
        subject: parsed.subject?.trim() || "Following up",
        message: parsed.message.trim(),
      };
    }
  } catch {
    // fall through to raw text
  }
  if (!content) throw new Error("The follow-up returned no usable result.");
  return { subject: "Following up", message: content };
}
