/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiBrowserRouteImport } from './routes/_authenticated/ai-browser'
import { Route as AuthenticatedFindLeadsRouteImport } from './routes/_authenticated/find-leads'
import { Route as AuthenticatedGigCreatorRouteImport } from './routes/_authenticated/gig-creator'
import { Route as AuthenticatedLeadsStoreRouteImport } from './routes/_authenticated/leads-store'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedTrainPitchRouteImport } from './routes/_authenticated/train-pitch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiBrowserRoute = AuthenticatedAiBrowserRouteImport.update({
  id: '/ai-browser',
  path: '/ai-browser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindLeadsRoute = AuthenticatedFindLeadsRouteImport.update({
  id: '/find-leads',
  path: '/find-leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGigCreatorRoute = AuthenticatedGigCreatorRouteImport.update({
  id: '/gig-creator',
  path: '/gig-creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsStoreRoute = AuthenticatedLeadsStoreRouteImport.update({
  id: '/leads-store',
  path: '/leads-store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainPitchRoute = AuthenticatedTrainPitchRouteImport.update({
  id: '/train-pitch',
  path: '/train-pitch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-browser': typeof AuthenticatedAiBrowserRoute
  '/find-leads': typeof AuthenticatedFindLeadsRoute
  '/gig-creator': typeof AuthenticatedGigCreatorRoute
  '/leads-store': typeof AuthenticatedLeadsStoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/train-pitch': typeof AuthenticatedTrainPitchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-browser': typeof AuthenticatedAiBrowserRoute
  '/find-leads': typeof AuthenticatedFindLeadsRoute
  '/gig-creator': typeof AuthenticatedGigCreatorRoute
  '/leads-store': typeof AuthenticatedLeadsStoreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/train-pitch': typeof AuthenticatedTrainPitchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-browser': typeof AuthenticatedAiBrowserRoute
  '/_authenticated/find-leads': typeof AuthenticatedFindLeadsRoute
  '/_authenticated/gig-creator': typeof AuthenticatedGigCreatorRoute
  '/_authenticated/leads-store': typeof AuthenticatedLeadsStoreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/train-pitch': typeof AuthenticatedTrainPitchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai-browser'
    | '/find-leads'
    | '/gig-creator'
    | '/leads-store'
    | '/profile'
    | '/storage'
    | '/train-pitch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai-browser'
    | '/find-leads'
    | '/gig-creator'
    | '/leads-store'
    | '/profile'
    | '/storage'
    | '/train-pitch'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ai-browser'
    | '/_authenticated/find-leads'
    | '/_authenticated/gig-creator'
    | '/_authenticated/leads-store'
    | '/_authenticated/profile'
    | '/_authenticated/storage'
    | '/_authenticated/train-pitch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-browser': {
      id: '/_authenticated/ai-browser'
      path: '/ai-browser'
      fullPath: '/ai-browser'
      preLoaderRoute: typeof AuthenticatedAiBrowserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find-leads': {
      id: '/_authenticated/find-leads'
      path: '/find-leads'
      fullPath: '/find-leads'
      preLoaderRoute: typeof AuthenticatedFindLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gig-creator': {
      id: '/_authenticated/gig-creator'
      path: '/gig-creator'
      fullPath: '/gig-creator'
      preLoaderRoute: typeof AuthenticatedGigCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads-store': {
      id: '/_authenticated/leads-store'
      path: '/leads-store'
      fullPath: '/leads-store'
      preLoaderRoute: typeof AuthenticatedLeadsStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/train-pitch': {
      id: '/_authenticated/train-pitch'
      path: '/train-pitch'
      fullPath: '/train-pitch'
      preLoaderRoute: typeof AuthenticatedTrainPitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiBrowserRoute: typeof AuthenticatedAiBrowserRoute
  AuthenticatedFindLeadsRoute: typeof AuthenticatedFindLeadsRoute
  AuthenticatedGigCreatorRoute: typeof AuthenticatedGigCreatorRoute
  AuthenticatedLeadsStoreRoute: typeof AuthenticatedLeadsStoreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedTrainPitchRoute: typeof AuthenticatedTrainPitchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiBrowserRoute: AuthenticatedAiBrowserRoute,
  AuthenticatedFindLeadsRoute: AuthenticatedFindLeadsRoute,
  AuthenticatedGigCreatorRoute: AuthenticatedGigCreatorRoute,
  AuthenticatedLeadsStoreRoute: AuthenticatedLeadsStoreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedTrainPitchRoute: AuthenticatedTrainPitchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
